---
title: "Data Cleaning Script"
format: html
---

```{r packages}
library(tidyverse)
library(rvest)
library(readr)
library(httr2)
library(purrr)
library(janitor)
library(stringr)
library(sf)
library(ggmap)
library(maps)
library(janitor)
```

```{r}
#Filter out Non Religious Organizations. Add Full Address Column to be Searched on. Trim Zip Code
eo_ny <- eo_ny|>
  filter(SUBSECTION == "03",
         FOUNDATION == "10")|>
  mutate(full_address = str_c(STREET, CITY, STATE, ZIP, sep = "_"),
         zip_code = str_extract(ZIP, pattern = "[0-9]{5}"))
```
```{r}
#Clean scraped zip code data from website
zip_codes|>
  mutate(row_num = row_number())|>
  filter(row_num == 14)|>
  unnest_longer(col = zip_scraped)|>
  filter(str_length(zip_scraped) > 1)|>
  mutate(zip_code = str_extract(zip_scraped, pattern = "[0-9]{5}"))|>
  mutate(city = str_remove(zip_scraped, pattern = "[0-9]{5}"))|>
  dplyr::select(zip_code, city) -> li_zip_codes
```

```{r}
#Filter eo_ny by zip code. 
li_churches <- li_zip_codes|>
  left_join(eo_ny, by = "zip_code")
```

```{r}
#filter out non Christian churches with keywords. 
li_churches|>
  mutate(ntee_code = str_extract(NTEE_CD, pattern = "[0-9]{2}"),
         ntee_code = as.numeric(ntee_code))|>
  filter(is.na(ntee_code) | between(ntee_code, 20, 22))|>
  filter(!str_detect(NAME, regex("islam", ignore_case = TRUE)),
         !str_detect(NAME, regex("school", ignore_case = TRUE)),
         !str_detect(NAME, regex("trust", ignore_case = TRUE)),
         !str_detect(NAME, regex("israel", ignore_case = TRUE)),
         !str_detect(NAME, regex("synagogue", ignore_case = TRUE)),
         !str_detect(NAME, regex("quran", ignore_case = TRUE)),
         !str_detect(NAME, regex("synogogue", ignore_case = TRUE)),
         !str_detect(NAME, regex("masjid", ignore_case = TRUE)),
         !str_detect(NAME, regex("jew", ignore_case = TRUE)),
         !str_detect(NAME, regex("torah", ignore_case = TRUE)),
         !is.na(NAME))|>
  distinct(NAME, .keep_all = TRUE)-> li_churches
```

```{r}
#filter by coordinates
map_data_li|>
  summarize(max_lat = max(lat),
            min_lat = min(lat),
            max_lon = max(long),
            min_lon = min(long)) -> li_boundaries

li_churches_coordinates|>
  unnest_longer(col = geo_loc)|>
  filter(!str_detect(geo_loc, pattern = "NA"))|>
  unnest_wider(col = geo_loc)|>
  distinct(EIN, .keep_all = TRUE)|>
  mutate(lat = as.numeric(lat),
    lon = as.numeric(lon))|>
  filter(between(lat, li_boundaries$min_lat, li_boundaries$max_lat),
         between(lon, li_boundaries$min_lon, li_boundaries$max_lon))-> map_data
```


```{r}
#function to clean data from the census calls. 
clean_census_api_call <- function(df){
  df <- tibble(df)
  colname <- names(df)[1]
  df |>
    unnest_longer(col = colname)|>
    unnest_wider(col = colname, names_sep = "_")|>
    distinct()|>
    row_to_names(1)|>
    select(-ends_with("A"))|>
    mutate(GEO_ID = str_remove_all(GEO_ID, pattern = "1500000US"))
}

cleaned_household <- clean_census_api_call(li_household_data)
cleaned_age <- clean_census_api_call(li_age_data)
cleaned_tenure <- clean_census_api_call(li_tenure_data)
cleaned_race <- clean_census_api_call(li_race_data)
cleaned_household_size <- clean_census_api_call(li_household_size_data)
cleaned_urban_rural <- clean_census_api_call(li_urban_rural)
cleaned_total_pop <- clean_census_api_call(li_total_population)

```

```{r}
#create dataframes to receive the column names
create_prepped_df <- function(df){
  total_cols <- length(colnames(df))
  end_col <- total_cols - 4
  df|>
    select(1:end_col)|>
    select(-2)
}

prepped_tenure <- create_prepped_df(cleaned_tenure)
prepped_age <- create_prepped_df(cleaned_age)
prepped_household <- create_prepped_df(cleaned_household)
prepped_race <- create_prepped_df(cleaned_race)
prepped_household_size <- create_prepped_df(cleaned_household_size)
prepped_urban_rural <- create_prepped_df(cleaned_urban_rural)
prepped_total_pop <- create_prepped_df(cleaned_total_pop)

```

```{r}
#add colnames to prepped dfs
colnames(prepped_tenure) <- tenure_cols[1, ]
colnames(prepped_age) <- age_cols[1, ]
colnames(prepped_household) <- household_cols[1, ]
colnames(prepped_race) <- race_cols[1, ]
colnames(prepped_household_size) <- household_size_cols[1, ]
colnames(prepped_urban_rural) <- urban_rural_cols[1, ]
colnames(prepped_total_pop) <- total_pop_cols[1, ]


#clean column names 
prepped_tenure <- clean_names(prepped_tenure)
prepped_age <- clean_names(prepped_age)
prepped_household <- clean_names(prepped_household)
prepped_race <- clean_names(prepped_race)
prepped_household_size <- clean_names(prepped_household_size)
prepped_urban_rural <- clean_names(prepped_urban_rural)
prepped_total_pop <- clean_names(prepped_total_pop)
```

```{r}
#create df of all census variables gathered
li_bg_census_data <- prepped_tenure |>
  inner_join(prepped_age, by = "geography")|>
  inner_join(prepped_household, by = "geography")|>
  inner_join(prepped_race, by = "geography")|>
  inner_join(prepped_household_size, by = "geography")|>
  inner_join(prepped_urban_rural, by = "geography")|>
  inner_join(prepped_total_pop, by = "geography")|>
  select(-total.x, -total.y, -total.x.x, -total.y.y, -total_not_defined_for_this_file)|>
  rename(total_population = total)|>
  relocate(total_population, .after = 1)
```

```{r}
#join block group data to get geometries 
li_bg_census_data <- li_bg_census_data |>
  inner_join(long_island_bg, by = c("geography" = "geoid"))

li_bg_census_data <- li_bg_census_data |>
  mutate(across(.cols = -c(geography, geometry),
                .fns = as.numeric))|>
  select(-namelsad, -mtfcc, -funcstat)
```

```{r}
#spacial join
map_data_sf <- st_as_sf(map_data, coords = c("lon", "lat"), crs = 4326)
li_bg_census_data <- st_as_sf(li_bg_census_data, sf_column_name = "geometry")
st_crs(li_bg_census_data) <- 4326

joined_data <- st_join(map_data_sf, li_bg_census_data, join = st_within)
```

```{r}
#clean up the joined_data for the final csv!
church_census_bg_data_final <- joined_data |>
  select(-c(ICO, city, ZIP, GROUP, SUBSECTION, AFFILIATION, CLASSIFICATION, RULING, DEDUCTIBILITY, FOUNDATION, ACTIVITY, ORGANIZATION, STATUS, TAX_PERIOD, ASSET_CD, INCOME_CD, FILING_REQ_CD, PF_FILING_REQ_CD, ACCT_PD, ASSET_AMT, INCOME_AMT, REVENUE_AMT, NTEE_CD, ntee_code, SORT_NAME, osm_type, boundingbox, class, type, importance, icon, geo_loc_id, geometry, geography))|>
  clean_names()
```

