---
title: "Data Analysis Script"
format: html
---

```{r packages}
library(ggplot2)
library(ggmap)
library(maps)
```


```{r}
map_data_li <- map_data("county", "new york")
map_data_li <- map_data_li |> filter(region == "new york", subregion %in% c("nassau", "suffolk", "queens", "bronx"))

ggplot() +
  geom_polygon(data = map_data_li, aes(x = long, y = lat, group = group),
               fill = "grey95", color = "black") +
  geom_point(data = map_data, aes(x = lon, y = lat),
             color = "blue", alpha = 0.6, size = 2) +
  coord_fixed(1.3) +
  labs(title = "Church Locations on Long Island, Queens, and Bronx") +
  theme_minimal()

```

```{r}
li_churches_coordinates|>
  unnest_longer(col = geo_loc)|>
  filter(!str_detect(geo_loc, pattern = "NA"))|>
  unnest_wider(col = geo_loc)|>
  distinct(EIN, .keep_all = TRUE)|>
  mutate(lat = as.numeric(lat),
    lon = as.numeric(lon))|>
  filter(between(lat, li_boundaries$min_lat, li_boundaries$max_lat),
         between(lon, li_boundaries$min_lon, li_boundaries$max_lon))|>
  
```

