---
title: "Data Import Script"
format: html
---

```{r packages}
library(tidyverse)
library(rvest)
library(readr)
library(httr2)
library(purrr)
library(janitor)
library(stringr)
library(sf)
library(ggmap)
library(maps)
library(keyring)
```

```{r}
#set keys
key_set(service = "census_api", username = "me")
key_set(service = "location_api", username = "me") 
```


```{r}
#irs data CSV
eo_ny <- read_csv(".data/imported_data/eo_ny.csv")
```

```{r}
#function to use LocationIQ API to match address to coordinates.

url <- "https://us1.locationiq.com/v1/search"
locationiq_key <- key_get(service = "location_api", username = "me")

geocode <- function(location){
  Sys.sleep(1)
  request(url)|>
    req_url_query(key = locationiq_key,
                  q = location,
                  format = "json")|>
    req_perform()|>
    resp_body_json()
}

safe_geocode <- purrr::possibly(
  geocode,
  otherwise = list(lat = NA, lon = NA)
)

```

```{r}
#use safe geocode function to get coordinates from addresses
li_churches_coordinates <- li_churches|>
  mutate(geo_loc = purrr::map(.x = full_address,
                       .f = safe_geocode,
                       .progress = TRUE))
```


```{r}
#import data for long and lat boundaries 
map_data_li <- map_data("county", "new york")
map_data_li <- map_data_li |> filter(region == "new york", subregion %in% c("nassau", "suffolk", "queens", "bronx"))
```


```{r}
#Scrape Long Island Zip Codes

zip_code_url <- "https://www.lifamilies.com/community/long-island-new-york-zip-codes.aspx"

read_html(zip_code_url)|>
  html_elements("div")|>
  html_text2()|>
  str_split("\n") -> zip_scraped

zip_codes <- tibble(zip_scraped)
```

```{r}
#shapefile imports
nassau_bg <- st_read("./data/imported_data/tl_2020_36059_bg20.shp") |>
  st_transform(4326)

suffolk_bg <- st_read("./data/imported_data/tl_2020_36059_bg20.shp")|>
  st_transform(4326)

long_island_bg <- bind_rows(nassau_bg, suffolk_bg)
long_island_bg |>
  clean_names()|>
  rename_with(~ str_replace_all(.x, "20$", ""))|>
  mutate(intptlat = str_remove_all(intptlat, "\\+")) -> long_island_bg
```

```{r}
#function get census data by geoid, group. 
get_dhc_by_geoid <- function(geoid, group, key) {
  state  <- stringr::str_sub(geoid, 1, 2)
  county <- stringr::str_sub(geoid, 3, 5)
  tract  <- stringr::str_sub(geoid, 6, 11)
  bg     <- stringr::str_sub(geoid, 12, 12)
  
  base_url <- "https://api.census.gov/data/2020/dec/dhc"
  
  request(base_url) |> 
    req_url_query(get = paste0("group(", group, ")"),
      `for` = paste0("block group:", bg),
      `in` = paste0("state:", state, " county:", county, " tract:", tract),
      key = key) |>
    req_perform()|>
    resp_body_json()
}
```


```{r}
#use get_dhc_by_geoid function to collect long_island census information. 
census_key = key_get(service = "census_api", username = "me")
li_race_data <- purrr::map(.x = long_island_bg$geoid,
                    ~ get_dhc_by_geoid(.x,
                                       "P6",
                                       census_key),
                    .progress = TRUE)

li_household_data <- purrr::map(.x = long_island_bg$geoid,
                                ~ get_dhc_by_geoid(.x,
                                                   "P16",
                                                   census_key),
                                .progress = TRUE)
li_age_data <- purrr::map(.x = long_island_bg$geoid,
                          ~ get_dhc_by_geoid(.x,
                                             "P13",
                                             census_key),
                          .progress = TRUE)
li_tenure_data <- purrr::map(.x = long_island_bg$geoid,
                            ~ get_dhc_by_geoid(.x,
                                               "H4",
                                               census_key),
                            .progress = TRUE)
li_household_size_data <- purrr::map(.x = long_island_bg$geoid,
                            ~ get_dhc_by_geoid(.x,
                                               "H9",
                                               census_key),
                            .progress = TRUE)
li_urban_rural <- purrr::map(.x = long_island_bg$geoid,
                            ~ get_dhc_by_geoid(.x,
                                               "H2",
                                               census_key),
                            .progress = TRUE)
li_total_population <- purrr::map(.x = long_island_bg$geoid,
                                  ~ get_dhc_by_geoid(.x,
                                                     "P1",
                                                     census_key),
                                  .progress = TRUE)
                                               
```

```{r}
#function to get the column names from the group variable page.
get_group_colnames <- function(group){
  base_url <- str_glue("https://api.census.gov/data/2020/dec/dhc/groups/", group, ".html")
  
  read_html(base_url)|>
    html_table() -> group_table
  
  group_table <- tibble(col = group_table)
  group_columns <- group_table[[1]][[1]]

  group_columns |>
    select(Label) |>
    pivot_wider(names_from = Label, values_from = Label)|>
    select(-1)|>
    select(-starts_with("Anno"))|>
    select(-starts_with("Geographic"))
}

age_cols <- get_group_colnames("P13")
household_cols <- get_group_colnames("P16")
race_cols <- get_group_colnames("P6")
tenure_cols <- get_group_colnames("H4")
household_size_cols <- get_group_colnames("H9")
urban_rural_cols <- get_group_colnames("H2")
total_pop_cols <- get_group_colnames("P1")
```


